services:
  digital_library:
    build: .
    restart: unless-stopped
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db
  db:
    image: postgis/postgis
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  postgres_data: